name: Deploy
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:

  call-build:
    uses: Quansight/conda-store-ui/.github/workflows/build.yml@main

  deploy-build:
    runs-on: ubuntu-latest
    needs: call-build

    steps:
      - name: Checkout
        uses: actions/Checkout@v3

      - name: Get dependencies for tsc
        run: yarn

      - name: Get release tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Generate package tarball
        run: yarn pack --filename conda-store-ui.tgz

      - name: Upload to npm
        run: yarn publish --verbose --access public --tag ${{ env.RELEASE_TAG }} conda-store-ui.tgz
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
