name: eslint check
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn eslint:check
    - name: Build artifacts
      run: yarn run webpack bundle
    - uses: actions/upload-artifact@v3
      with:
        name: webpack-bundle
        path: dist/
